### ISSUE TITLE
Two instances on same machine

### ISSUE THREAD

**Issue by vico93** [TediCross/TediCross#143]
I'm trying to run two instances simultaneously on my raspberry pi.
The first one sync the `#general` channel of my discord server with a telegram group, the secont syncs `#dev` of same server but with another telegram group. Each instance have its own Discord and Telegram bot accounts respectively, not sharing any.

Although both are relaying and have almost the same parameters on `settings.yaml` (except tokens and chat/group ids) the most recent instance i set up (the `#dev` to second group) are posting this annoying message on `#general` channel (not supposely to be there, it syncs with `#dev`):
![image](https://user-images.githubusercontent.com/3485505/89700211-d7171e80-d902-11ea-8ed7-d130b57fbbec.png)

The oldest instance (and sighly outdated in relation of this git repository) doesnt have any nagging messages like this.

I already checked and in both instances the IDs (discord between single quotes, telegram starting with `-`) on settings.yaml are correct, like said in README.

The only other thing i found was in `journalctl` of the second instance this missing permissions error:
```
 (node:1600) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
Aug 07 23:00:12 VICO-PI bot_stiggs[1585]:     at RequestHandler.execute (/trecos/bots/stiggs_tedicross/node_modules/discord.js/src/rest/RequestHandler.js:170:25)
Aug 07 23:00:12 VICO-PI bot_stiggs[1585]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Aug 07 23:00:12 VICO-PI bot_stiggs[1585]: (Use `node --trace-warnings ...` to show where the warning was created)
Aug 07 23:00:12 VICO-PI bot_stiggs[1585]: (node:1600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of
Aug 07 23:00:12 VICO-PI bot_stiggs[1585]: (node:1600) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that
```
... what i find strangely because i've added the bot on discord using the same permissions the invite link on readme have, and the instance is relaying chat normally.

What could be the issue?

**Comment by Suppen** [comment]
First, having two instances is unneccesary. You can have multiple bridges on one pair of bots. It should, however, not be a problem to have multiple instances.

Earlier, before version 0.9.9, which was released 2019-11-08, you had to configure each bridge with both the Discord Server ID and Channel ID. The reason for this was to tell the bot which server to not spam its "This is an instance..." message in.
In version 0.9.9 and later, you just supply the Channel ID, and the Discord side of TediCross automatically figures out the Server IDs belonging to those channels.
You mentioned having different version on the two instances. Could this be the reason? You can check the version by running `npm version`. It will show TediCross' version, along with a lot of other versions.

The "Missing Permissions" message is probably because of channel permissions. Sometimes it is necessary to set the permissions per channel. Right click on the channels, go to "Permissions", and check what permissions the bot has. It needs at minimum "Read" for D2T, and "Send" for T2D. "Manage messages", "Embed Links", "Attach files" and "Read Message History" are also used by it.

You should also know that TediCross MUST be updated to v0.10.x before November to continue working, as Discord changes from discordapp.com to just discord.com then.

**Comment by vico93** [comment]
>First, having two instances is unneccesary. You can have multiple bridges on one pair of bots. It should, however, not be a problem to have multiple instances.

Lord, i forgot is entirely possible to have multiple bridges in a single instance. I will try to update the first instance and then add on it the other bridge. If nothing amiss happens, i will close it. Thanks!

**Comment by vico93** [comment]
Closing it in favour of #144
