### ISSUE TITLE
Telegram fetch old messages

### ISSUE THREAD

**Issue by CaneTLOTW** [TediCross/TediCross#174]
Configured the server with skipOldMessages = false for Telegram.
However, no old messages from Telegram are synced.

**Comment by Suppen** [comment]
Telegram bots will receive all messages which have arrived since it last checked, and cannot get any from before that. In practice this means it will only relay messages which arrived since it was turned off. It also doesn't get any messages older than 24 hours*, regardless of when it last checked.

Does this match your observations?

* I might be wrong about the number of hours, but there is a limit.

**Comment by CaneTLOTW** [comment]
OK, was hoping to use this to backup the whole Telegram history ;)

any chance to do this, even if it gets ugly --> messages in wrong order?

**Comment by trgwii** [comment]
You can use the Telegram Export function to back up the history to a file, will that suit your needs?

**Comment by CaneTLOTW** [comment]
Planning to migarte the Telegram group to discord.
And would like to have a backup of the group in Discord.

The export would only be locally for me...

**Comment by trgwii** [comment]
You could post your export in Discord as a file

**Comment by CaneTLOTW** [comment]
files, pictures and formatting of the html will be missing....

So, no chance to tweak this to pull old posts?

**Comment by Suppen** [comment]
Literally impossible for Telegram. If you find the message ID of an old Discord message, you can theoretically modify the `lastMessageIds.json` file in `data/` to fetch all Discord messages after that.

**Comment by CaneTLOTW** [comment]
Ok, understood
