### ISSUE TITLE
File is too big to handle

### ISSUE THREAD

**Issue by Solomag** [TediCross/TediCross#316]
I propose to introduce a parameter that would disable these notifications, since they are generally obvious and as an alternative to add the ability to compress files to be able to transfer them.

P. S. I mean at least for video files which takes less than 50 mb

![Screenshot_20230628-083329](https://github.com/TediCross/TediCross/assets/33348398/215a15b7-aa2e-40b3-9b1a-0c44965cd228)

**Comment by Fabian42** [comment]
The real issue is usually that the limit on the Discord side is not usually what TeDiCross believes it to be, because that's a hardcoded number.

Compressing a video to exactly the right size with minimal quality loss is not trivial. I have a script for it here: https://github.com/Fabian42/bash_scripts/blob/master/shrink
But that runs for many times the duration of the video, even on a reasonably powerful computer, just for the "crf" parameter. It doesn't even attempt reducing resolution, framerate, audio quality, colour range or anything else, even though that can often give better results. Adding these features will be very complicated and make the script run even longer.
Currently TeDiCross is extremely lightweight, it can run on the most basic hardware without problems. If a compression feature is added, it should be off by default and have many warnings attached to it.
