### ISSUE TITLE
Telegram Albums Order in Discord

### ISSUE THREAD

**Issue by MyrTheMoth** [TediCross/TediCross#45]
Telegram has now released the Album update to desktops as well, something they rolled out to mobile clients a while ago

I've noticed the pictures work just fine when TediCross sends the album pictures to Discord as individual messages, but the only issue is that they are sent out of order

So if it is doable to acquire the order of photos in an album

"As a discord user I'd like Telegram Album Photos to be sent to Discord in the same order as in the Telegram Album"

**Comment by Suppen** [comment]
This is part of a larger synchronization problem in TediCross. It is usually not noticeable because the delays are too short for humans to react to, but when sending a picture with caption, or sending multiple messages very quickly, they sometimes appear out of order.

This is caused by the bot working asynchronously. Whenever it receives a message, it processes it and forwards it. Then it takes the next message and does the same. It does not wait for confirmation that the previous message was correctly received.

Fixing this can be problematic. I can quite easily implement a sending queue, which waits for the previous message to be confirmed before sending the next one, but when it comes to files (like pictures), this might become unbearable.

As you might have noticed, it often takes a few seconds for a picture or other file to go through the bot.  This is because the bot first has to download it, and then send it out again. Let's say it takes 2 seconds to clear a picture, and someone sends an album of 10 pictures. That's 20 seconds before the bot has forwarded them all. Messages which arrived after the album was sent are also put in the queue, so they will also be delayed by 20 seconds

It also has to keep the pictures in RAM while waiting to send them. This shouldn't be a big problem, but could potentially take down a raspberry pi or cheap VPS hosting the bot.


That being said, I'm planning a big rewrite of the bot soon, to be released sometime after April. The bot currently uses promises to handle async programming, but async/await has been available in EcmaScript some time. This makes the code neater and makes async programming easier. I might be able to sneak in some more message synchronization.

The reason I haven't already done this is that node 6, which is the lowest version the bot runs on, does not support it. It requires everyone to upgrade to node 8 or higher. Node 6 goes out of support in April, so everyone HAS to upgrade then anyway.
