### ISSUE TITLE
[Feature request] Option to delay the messages

### ISSUE THREAD

**Issue by peerchemist** [TediCross/TediCross#89]
This is useful when T2D as T has various specialized anti-spam bots, simple delay by 0.5s or 1s will stop the TediCross to carry over the spam as spam will get deleted by then.

What I am saying is option to delay T2D <read> by some offset.

**Comment by markthewolf90** [comment]
Last I knew, bots couldn't interact with other bots in Telegram.

**Comment by peerchemist** [comment]
That is not relevant here.

**Comment by trgwii** [comment]
Delay won't stop TediCross form carrying over spam, since TediCross will receive and forward even deleted messages. Telegram bots have no way to detect if a message was deleted on Telegram, so it will receive ALL messages, including those deleted by other anti-spam bots on Telegram. Telegram Support has been contacted numerous times about this by TediCross users, but feel free to tell them you also have this problem, and maybe they'll add some feature to detect deletion of messages: [@BotSupport](https://t.me/BotSupport)
